In [1]:
import os

In [2]:
files = os.listdir('data/')
files

['b19416acd7a4a1e9391f17095a0bbc7e_export.csv']

In [3]:
import pandas
import numpy as np

# Electicity Data

## read csv from taipower

In [4]:
df = pandas.read_csv(os.path.join('data', files[0]))

df

日期  淨尖峰供電能力(MW)  尖峰負載(MW)  備轉容量(MW)  備轉容量率(%)  工業用電(百萬度)  \
0    20190101        26429     23872    2557.0     10.71    279.870   
1    20190102        30047     28148    1899.0      6.75    323.080   
2    20190103        30343     28452    1891.0      6.65    336.597   
3    20190104        30301     28490    1811.0      6.36    339.020   
4    20190105        27957     26054    1903.0      7.30    315.825   
..        ...          ...       ...       ...       ...        ...   
665  20201027        35071     31669    3402.0     10.74    362.462   
666  20201028        35429     31959    3470.0     10.86    365.469   
667  20201029        34978     31271    3707.0     11.86    362.440   
668  20201030        34479     30264    4215.0     13.93    351.492   
669  20201031        30482     26763    3719.0     13.90    319.096   

     民生用電(百萬度)  核一#1(萬瓩)  核一#2(萬瓩)  核二#1(萬瓩)  ...   大觀二    明潭   碧海   立霧   龍澗  \
0      192.192         0         0      98.4  ...  16.0  54.0  0.0  1.2  3.0   
1      221.864         0         0      98.5  ...  29.9  52.3  0.0  1.2  2.0   
2      231.146         0         0      98.7  ...  14.3  65.5  0.0  1.4  1.2   
3      232.810         0         0      98.7  ...  18.1  52.3  0.0  1.4  1.4   
4      216.882         0         0      98.7  ...  30.4  57.6  0.0  1.3  3.0   
..         ...       ...       ...       ...  ...   ...   ...  ...  ...  ...   
665    309.405         0         0      98.1  ...  43.5  63.8  4.8  1.4  1.9   
666    311.972         0         0      98.0  ...  14.4  48.0  4.0  1.2  1.4   
667    309.387         0         0      97.8  ...  20.5  50.0  1.0  1.2  1.3   
668    300.041         0         0      97.8  ...  12.1  32.3  2.0  1.2  1.5   
669    272.388         0         0      98.1  ...  29.2  81.5  3.2  1.2  3.0   

      卓蘭   水里  其他小水力  風力發電  太陽能發電  
0    2.2  0.0   24.3  50.9    0.0  
1    2.1  0.0   23.4  37.9    0.0  
2    2.0  0.1   24.1  41.6    0.0  
3    0.0  0.0   19.3  12.4   11.0  
4    2.9  0.0   23.9  18.5    0.0  
..   ...  ...    ...   ...    ...  
665  1.7  0.8   13.9  34.6   41.5  
666  0.0  0.5   13.7  58.8  161.6  
667  0.0  0.5   16.2  60.8  143.3  
668  0.0  0.5   16.5  60.1  207.5  
669  1.7  0.4   24.1  55.2    0.0  

[670 rows x 71 columns]

##  check what columns we have

In [5]:
df.columns

Index(['日期', '淨尖峰供電能力(MW)', '尖峰負載(MW)', '備轉容量(MW)', '備轉容量率(%)', '工業用電(百萬度)',
       '民生用電(百萬度)', '核一#1(萬瓩)', '核一#2(萬瓩)', '核二#1(萬瓩)', '核二#2(萬瓩)', '核三#1',
       '核三#2', '林口#1', '林口#2', '林口#3', '台中#1', '台中#2', '台中#3', '台中#4', '台中#5',
       '台中#6', '台中#7', '台中#8', '台中#9', '台中#10', '興達#1', '興達#2', '興達#3', '興達#4',
       '大林#1', '大林#2', '和平#1', '和平#2', '麥寮#1', '麥寮#2', '麥寮#3', '汽電共生',
       '大潭 (#1-#6)', '通霄 (#1-#6)', '興達 (#1-#5)', '南部 (#1-#4)', '大林(#5-#6)',
       '海湖 (#1-#2)', '國光 #1', '新桃#1', '星彰#1', '星元#1', '嘉惠#1', '豐德(#1-#2)',
       '協和 (#1-#4)', '氣渦輪', '離島', '德基', '青山', '谷關', '天輪', '馬鞍', '萬大', '大觀',
       '鉅工', '大觀二', '明潭', '碧海', '立霧', '龍澗', '卓蘭', '水里', '其他小水力', '風力發電',
       '太陽能發電'],
      dtype='object')

## check if containing NaN

In [6]:
for col in df.columns:
    print(col)
    print(np.where(np.isnan(df[col])))

日期
(array([], dtype=int64),)
淨尖峰供電能力(MW)
(array([], dtype=int64),)
尖峰負載(MW)
(array([], dtype=int64),)
備轉容量(MW)
(array([], dtype=int64),)
備轉容量率(%)
(array([], dtype=int64),)
工業用電(百萬度)
(array([], dtype=int64),)
民生用電(百萬度)
(array([], dtype=int64),)
核一#1(萬瓩)
(array([], dtype=int64),)
核一#2(萬瓩)
(array([], dtype=int64),)
核二#1(萬瓩)
(array([], dtype=int64),)
核二#2(萬瓩)
(array([], dtype=int64),)
核三#1
(array([], dtype=int64),)
核三#2
(array([], dtype=int64),)
林口#1
(array([], dtype=int64),)
林口#2
(array([], dtype=int64),)
林口#3
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),)
台中#1
(array([], dtype=int64),)
台中#2
(array([], dtype=int64),)
台中#3
(array([], dtype=int64),)
台中#4
(array([], dtype=int64),)
台中#5
(array([], dtype=int64),)
台中#6
(array([], dtype=int64),)
台中#7
(array([], dtype=int64),)
台中#8
(array([], dtype=int64),)
台中#9
(array([], dtype=int64),)
台中#10
(array([], dtype=int64),)
興達#1
(array([], dtype=int64),)
興達#

In [7]:
#fill the NaN value with mean
from sklearn.impute import SimpleImputer
import numpy as np

ipt = SimpleImputer(missing_values=np.NaN, strategy='mean')
df = pandas.DataFrame(ipt.fit_transform(df),columns=df.columns)

#  Make Training data

In [13]:
#prepare the training data
train_data = df[:-10]
train_label = pandas.DataFrame(df['備轉容量(MW)'])[-10:]

In [14]:
train_data

日期  淨尖峰供電能力(MW)  尖峰負載(MW)  備轉容量(MW)  備轉容量率(%)  工業用電(百萬度)  \
0    20190101.0      26429.0   23872.0    2557.0     10.71    279.870   
1    20190102.0      30047.0   28148.0    1899.0      6.75    323.080   
2    20190103.0      30343.0   28452.0    1891.0      6.65    336.597   
3    20190104.0      30301.0   28490.0    1811.0      6.36    339.020   
4    20190105.0      27957.0   26054.0    1903.0      7.30    315.825   
..          ...          ...       ...       ...       ...        ...   
655  20201017.0      32108.0   28021.0    4087.0     14.59    339.706   
656  20201018.0      30516.0   26570.0    3946.0     14.85    314.197   
657  20201019.0      35551.0   31046.0    4505.0     14.51    351.808   
658  20201020.0      35876.0   31632.0    4244.0     13.42    362.755   
659  20201021.0      35676.0   32367.0    3309.0     10.22    371.917   

     民生用電(百萬度)  核一#1(萬瓩)  核一#2(萬瓩)  核二#1(萬瓩)  ...   大觀二    明潭   碧海   立霧   龍澗  \
0      192.192       0.0       0.0      98.4  ...  16.0  54.0  0.0  1.2  3.0   
1      221.864       0.0       0.0      98.5  ...  29.9  52.3  0.0  1.2  2.0   
2      231.146       0.0       0.0      98.7  ...  14.3  65.5  0.0  1.4  1.2   
3      232.810       0.0       0.0      98.7  ...  18.1  52.3  0.0  1.4  1.4   
4      216.882       0.0       0.0      98.7  ...  30.4  57.6  0.0  1.3  3.0   
..         ...       ...       ...       ...  ...   ...   ...  ...  ...  ...   
655    289.981       0.0       0.0      98.0  ...  28.8  66.1  5.6  1.2  2.7   
656    268.205       0.0       0.0      79.2  ...  29.4  81.7  3.9  1.2  1.1   
657    300.311       0.0       0.0      97.9  ...  16.5  48.6  6.0  1.2  1.3   
658    309.655       0.0       0.0      98.0  ...  15.2  51.1  5.2  1.2  1.1   
659    317.477       0.0       0.0      97.9  ...  20.5  64.6  5.9  1.0  2.0   

      卓蘭   水里  其他小水力  風力發電  太陽能發電  
0    2.2  0.0   24.3  50.9    0.0  
1    2.1  0.0   23.4  37.9    0.0  
2    2.0  0.1   24.1  41.6    0.0  
3    0.0  0.0   19.3  12.4   11.0  
4    2.9  0.0   23.9  18.5    0.0  
..   ...  ...    ...   ...    ...  
655  1.7  0.6   24.3  66.4    0.0  
656  1.8  0.5   26.4  66.7    0.0  
657  1.8  0.6   20.4  66.1   39.4  
658  1.8  0.5   20.9  67.7   98.8  
659  1.8  0.8   20.6  55.8   21.0  

[660 rows x 71 columns]

In [16]:
train_label

備轉容量(MW)
660    4341.0
661    4003.0
662    3892.0
663    4025.0
664    3503.0
665    3402.0
666    3470.0
667    3707.0
668    4215.0
669    3719.0

## normalize data

In [21]:
from sklearn.preprocessing import normalize

train_data_norm = normalize(train_data, axis=0)

In [22]:
train_data_norm

array([[0.03891534, 0.03018594, 0.03056742, ..., 0.04497055, 0.06165892,
        0.        ],
       [0.03891534, 0.03431825, 0.03604272, ..., 0.04330498, 0.04591107,
        0.        ],
       [0.03891534, 0.03465632, 0.03643198, ..., 0.04460043, 0.05039315,
        0.        ],
       ...,
       [0.03893638, 0.04060465, 0.03975352, ..., 0.03775306, 0.0800718 ,
        0.01475169],
       [0.03893638, 0.04097585, 0.04050388, ..., 0.03867838, 0.08201   ,
        0.03699156],
       [0.03893639, 0.04074742, 0.04144503, ..., 0.03812319, 0.06759466,
        0.00786258]])

In [23]:
train_label

備轉容量(MW)
660    4341.0
661    4003.0
662    3892.0
663    4025.0
664    3503.0
665    3402.0
666    3470.0
667    3707.0
668    4215.0
669    3719.0

## train test split

In [77]:
#split the data into 70% training and 30% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_data,train_label,test_size=0.3)

In [78]:
print(len(X_train), len(X_test), len(y_train), len(y_test) )

469 201 469 201


# test fit model

In [79]:
from sklearn.metrics import mean_squared_error

In [80]:
from sklearn.linear_model import LinearRegression
linearR_model = LinearRegression()
linearR_model.fit(X_train,y_train)
linear_result = linearR_model.predict(X_test)

print("linear regression model score:")
linearR_model.score(X_test,y_test)

linear regression model score:


0.9710050377909486

In [81]:
y_train

備轉容量(MW)
134    2253.0
542    3907.0
89     2297.0
602    3812.0
448    4125.0
..        ...
133    2131.0
500    3622.0
118     221.1
495    3015.0
290    4810.0

[469 rows x 1 columns]

In [82]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,linear_result)

39816.16490480941

In [83]:
linear_result

array([[3106.67993331],
       [3877.13323753],
       [3970.9444293 ],
       [4190.57417761],
       [4020.12304439],
       [3253.24012806],
       [3457.87116207],
       [5999.23460254],
       [3182.24606264],
       [4226.65961547],
       [1726.12706718],
       [5283.48788141],
       [1567.40378049],
       [2358.70081905],
       [ 761.90384459],
       [4083.56297988],
       [3810.79246946],
       [5918.71909971],
       [3503.67675245],
       [3842.39416737],
       [3607.44740415],
       [3299.14132246],
       [4021.14487692],
       [4160.15985772],
       [1875.9564507 ],
       [3926.00196069],
       [4391.37297237],
       [3598.74906846],
       [3537.10280903],
       [4965.8229328 ],
       [2108.67650201],
       [3618.67732562],
       [2970.75973477],
       [2209.08723971],
       [3651.38494815],
       [2275.38396298],
       [4530.37705847],
       [3432.03633578],
       [3307.84238993],
       [3336.80251496],
       [5081.86086094],
       [4541.264