In [1]:
import os

In [2]:
files = os.listdir('data/')
files

['b19416acd7a4a1e9391f17095a0bbc7e_export.csv']

In [3]:
import pandas
import numpy as np

# Electicity Data

## read csv from taipower

In [4]:
df = pandas.read_csv(os.path.join('data', files[0]))

df

日期  淨尖峰供電能力(MW)  尖峰負載(MW)  備轉容量(MW)  備轉容量率(%)  工業用電(百萬度)  \
0    20190101        26429     23872    2557.0     10.71    279.870   
1    20190102        30047     28148    1899.0      6.75    323.080   
2    20190103        30343     28452    1891.0      6.65    336.597   
3    20190104        30301     28490    1811.0      6.36    339.020   
4    20190105        27957     26054    1903.0      7.30    315.825   
..        ...          ...       ...       ...       ...        ...   
665  20201027        35071     31669    3402.0     10.74    362.462   
666  20201028        35429     31959    3470.0     10.86    365.469   
667  20201029        34978     31271    3707.0     11.86    362.440   
668  20201030        34479     30264    4215.0     13.93    351.492   
669  20201031        30482     26763    3719.0     13.90    319.096   

     民生用電(百萬度)  核一#1(萬瓩)  核一#2(萬瓩)  核二#1(萬瓩)  ...   大觀二    明潭   碧海   立霧   龍澗  \
0      192.192         0         0      98.4  ...  16.0  54.0  0.0  1.2  3.0   
1      221.864         0         0      98.5  ...  29.9  52.3  0.0  1.2  2.0   
2      231.146         0         0      98.7  ...  14.3  65.5  0.0  1.4  1.2   
3      232.810         0         0      98.7  ...  18.1  52.3  0.0  1.4  1.4   
4      216.882         0         0      98.7  ...  30.4  57.6  0.0  1.3  3.0   
..         ...       ...       ...       ...  ...   ...   ...  ...  ...  ...   
665    309.405         0         0      98.1  ...  43.5  63.8  4.8  1.4  1.9   
666    311.972         0         0      98.0  ...  14.4  48.0  4.0  1.2  1.4   
667    309.387         0         0      97.8  ...  20.5  50.0  1.0  1.2  1.3   
668    300.041         0         0      97.8  ...  12.1  32.3  2.0  1.2  1.5   
669    272.388         0         0      98.1  ...  29.2  81.5  3.2  1.2  3.0   

      卓蘭   水里  其他小水力  風力發電  太陽能發電  
0    2.2  0.0   24.3  50.9    0.0  
1    2.1  0.0   23.4  37.9    0.0  
2    2.0  0.1   24.1  41.6    0.0  
3    0.0  0.0   19.3  12.4   11.0  
4    2.9  0.0   23.9  18.5    0.0  
..   ...  ...    ...   ...    ...  
665  1.7  0.8   13.9  34.6   41.5  
666  0.0  0.5   13.7  58.8  161.6  
667  0.0  0.5   16.2  60.8  143.3  
668  0.0  0.5   16.5  60.1  207.5  
669  1.7  0.4   24.1  55.2    0.0  

[670 rows x 71 columns]

##  check what columns we have

In [5]:
df.columns

Index(['日期', '淨尖峰供電能力(MW)', '尖峰負載(MW)', '備轉容量(MW)', '備轉容量率(%)', '工業用電(百萬度)',
       '民生用電(百萬度)', '核一#1(萬瓩)', '核一#2(萬瓩)', '核二#1(萬瓩)', '核二#2(萬瓩)', '核三#1',
       '核三#2', '林口#1', '林口#2', '林口#3', '台中#1', '台中#2', '台中#3', '台中#4', '台中#5',
       '台中#6', '台中#7', '台中#8', '台中#9', '台中#10', '興達#1', '興達#2', '興達#3', '興達#4',
       '大林#1', '大林#2', '和平#1', '和平#2', '麥寮#1', '麥寮#2', '麥寮#3', '汽電共生',
       '大潭 (#1-#6)', '通霄 (#1-#6)', '興達 (#1-#5)', '南部 (#1-#4)', '大林(#5-#6)',
       '海湖 (#1-#2)', '國光 #1', '新桃#1', '星彰#1', '星元#1', '嘉惠#1', '豐德(#1-#2)',
       '協和 (#1-#4)', '氣渦輪', '離島', '德基', '青山', '谷關', '天輪', '馬鞍', '萬大', '大觀',
       '鉅工', '大觀二', '明潭', '碧海', '立霧', '龍澗', '卓蘭', '水里', '其他小水力', '風力發電',
       '太陽能發電'],
      dtype='object')

In [6]:
len(df.columns)

71

## check if containing NaN

In [7]:
for col in df.columns:
    print(col)
    print(np.where(np.isnan(df[col])))

日期
(array([], dtype=int64),)
淨尖峰供電能力(MW)
(array([], dtype=int64),)
尖峰負載(MW)
(array([], dtype=int64),)
備轉容量(MW)
(array([], dtype=int64),)
備轉容量率(%)
(array([], dtype=int64),)
工業用電(百萬度)
(array([], dtype=int64),)
民生用電(百萬度)
(array([], dtype=int64),)
核一#1(萬瓩)
(array([], dtype=int64),)
核一#2(萬瓩)
(array([], dtype=int64),)
核二#1(萬瓩)
(array([], dtype=int64),)
核二#2(萬瓩)
(array([], dtype=int64),)
核三#1
(array([], dtype=int64),)
核三#2
(array([], dtype=int64),)
林口#1
(array([], dtype=int64),)
林口#2
(array([], dtype=int64),)
林口#3
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),)
台中#1
(array([], dtype=int64),)
台中#2
(array([], dtype=int64),)
台中#3
(array([], dtype=int64),)
台中#4
(array([], dtype=int64),)
台中#5
(array([], dtype=int64),)
台中#6
(array([], dtype=int64),)
台中#7
(array([], dtype=int64),)
台中#8
(array([], dtype=int64),)
台中#9
(array([], dtype=int64),)
台中#10
(array([], dtype=int64),)
興達#1
(array([], dtype=int64),)
興達#

In [8]:
#fill the NaN value with mean
from sklearn.impute import SimpleImputer
import numpy as np

ipt = SimpleImputer(missing_values=np.NaN, strategy='mean')
df = pandas.DataFrame(ipt.fit_transform(df),columns=df.columns)

#  Make Training data

In [9]:
#prepare the training data
train_data = df[:-7]
train_label = pandas.DataFrame(df['備轉容量(MW)'])[-7:]

In [10]:
np.array(train_label)

array([[4025.],
       [3503.],
       [3402.],
       [3470.],
       [3707.],
       [4215.],
       [3719.]])

In [11]:
train_data

日期  淨尖峰供電能力(MW)  尖峰負載(MW)  備轉容量(MW)  備轉容量率(%)  工業用電(百萬度)  \
0    20190101.0      26429.0   23872.0    2557.0     10.71    279.870   
1    20190102.0      30047.0   28148.0    1899.0      6.75    323.080   
2    20190103.0      30343.0   28452.0    1891.0      6.65    336.597   
3    20190104.0      30301.0   28490.0    1811.0      6.36    339.020   
4    20190105.0      27957.0   26054.0    1903.0      7.30    315.825   
..          ...          ...       ...       ...       ...        ...   
658  20201020.0      35876.0   31632.0    4244.0     13.42    362.755   
659  20201021.0      35676.0   32367.0    3309.0     10.22    371.917   
660  20201022.0      35543.0   31202.0    4341.0     13.91    361.320   
661  20201023.0      33701.0   29698.0    4003.0     13.48    346.754   
662  20201024.0      30683.0   26791.0    3892.0     14.53    319.174   

     民生用電(百萬度)  核一#1(萬瓩)  核一#2(萬瓩)  核二#1(萬瓩)  ...   大觀二    明潭   碧海   立霧   龍澗  \
0      192.192       0.0       0.0      98.4  ...  16.0  54.0  0.0  1.2  3.0   
1      221.864       0.0       0.0      98.5  ...  29.9  52.3  0.0  1.2  2.0   
2      231.146       0.0       0.0      98.7  ...  14.3  65.5  0.0  1.4  1.2   
3      232.810       0.0       0.0      98.7  ...  18.1  52.3  0.0  1.4  1.4   
4      216.882       0.0       0.0      98.7  ...  30.4  57.6  0.0  1.3  3.0   
..         ...       ...       ...       ...  ...   ...   ...  ...  ...  ...   
658    309.655       0.0       0.0      98.0  ...  15.2  51.1  5.2  1.2  1.1   
659    317.477       0.0       0.0      97.9  ...  20.5  64.6  5.9  1.0  2.0   
660    308.430       0.0       0.0      97.9  ...  13.2  33.9  6.0  1.6  1.7   
661    295.997       0.0       0.0      97.8  ...  15.8  48.9  6.0  1.6  1.8   
662    272.453       0.0       0.0      97.8  ...  28.8  80.8  5.0  1.6  1.5   

      卓蘭   水里  其他小水力  風力發電  太陽能發電  
0    2.2  0.0   24.3  50.9    0.0  
1    2.1  0.0   23.4  37.9    0.0  
2    2.0  0.1   24.1  41.6    0.0  
3    0.0  0.0   19.3  12.4   11.0  
4    2.9  0.0   23.9  18.5    0.0  
..   ...  ...    ...   ...    ...  
658  1.8  0.5   20.9  67.7   98.8  
659  1.8  0.8   20.6  55.8   21.0  
660  0.0  0.5   20.9  64.9  159.7  
661  1.7  0.7   23.3  65.7   14.9  
662  4.0  0.7   27.0  50.1    0.0  

[663 rows x 71 columns]

In [12]:
train_label

備轉容量(MW)
663    4025.0
664    3503.0
665    3402.0
666    3470.0
667    3707.0
668    4215.0
669    3719.0

## normalize data

In [13]:
from sklearn.preprocessing import normalize

train_data_norm = normalize(train_data, axis=0)

In [14]:
train_data_norm

array([[0.03882714, 0.03012038, 0.03050314, ..., 0.04483954, 0.06116553,
        0.        ],
       [0.03882714, 0.03424372, 0.03596692, ..., 0.04317882, 0.04554368,
        0.        ],
       [0.03882715, 0.03458106, 0.03635537, ..., 0.04447049, 0.0499899 ,
        0.        ],
       ...,
       [0.03884814, 0.04050735, 0.03986926, ..., 0.0385657 , 0.07798905,
        0.05968551],
       [0.03884815, 0.03840808, 0.03794748, ..., 0.04299429, 0.0789504 ,
        0.00556865],
       [0.03884815, 0.03496855, 0.03423298, ..., 0.04982172, 0.06020418,
        0.        ]])

In [15]:
train_label

備轉容量(MW)
663    4025.0
664    3503.0
665    3402.0
666    3470.0
667    3707.0
668    4215.0
669    3719.0

## dataset

In [16]:
from sklearn.preprocessing import normalize
from torch.utils.data import DataLoader
from torch.utils.data import Dataset as BaseDataset


In [17]:

class Dataset(BaseDataset):
    def __init__(
        self,
        train_data,
        apply_normalize = False,
    ):
        #prepare the training data and label
        self.train_label = np.array(train_data['備轉容量(MW)'])
        if not normalize:
            self.train_data = np.array(train_data)
        else:
           self.train_data = np.array(normalize(train_data, axis=0))
    
    def __getitem__(self, i):
        x = self.train_data[:100+i]
        y = self.train_label[100+i:100+i+7]
        
        return x, y
    
    def __len__(self):
        return len(self.train_data) - 200

In [18]:
dataset = Dataset(df)

In [19]:
x,y = dataset[0]

In [20]:
x.shape

(100, 71)

In [21]:
y.shape

(7,)

In [22]:
len(dataset)

470

# Model

In [23]:
import torch
import torch.nn as nn

In [30]:
class Model(nn.Module):
    def __init__(self, hidden_size=100, num_layers=5):
        super(Model,self).__init__()
        
        self.rnn = nn.GRU(71, hidden_size, num_layers)
        self.h0 = torch.randn(num_layers, 1, hidden_size, requires_grad=True)
        if torch.cuda.is_available():
            self.h0 = self.h0.cuda()
        
        self.fc1 = nn.Linear(9, 128)
        self.fc2 = nn.Linear(128, 512)
        self.fc3 = nn.Linear(512, 128)
        self.fc4 = nn.Linear(128, 7)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.01)
        self.avgpool = nn.AdaptiveAvgPool2d((3,3))
        
    def forward(self, x):
        output, hn = self.rnn(x, self.h0)
        output = torch.transpose(output, 0,1)
        output = self.avgpool(output)
        x = torch.flatten(output)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc3(x)
        x = self.relu(x)
        x = self.fc4(x)
#         x = torch.sigmoid(x)
        
#         return x* self.norm_factor
        return x

In [32]:
model = Model(num_layers=100)

In [33]:
np.max(np.array(train_label))

4215.0

In [34]:
x,y = dataset[0]
x = torch.tensor(x, dtype=torch.float).unsqueeze(dim=1)
y = torch.tensor(y, dtype=torch.float)

In [35]:
x.shape

torch.Size([100, 1, 71])

In [36]:
y.shape

torch.Size([7])

In [37]:
model.cuda()

Model(
  (rnn): GRU(71, 100, num_layers=100)
  (fc1): Linear(in_features=9, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=128, bias=True)
  (fc4): Linear(in_features=128, out_features=7, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.01, inplace=False)
  (avgpool): AdaptiveAvgPool2d(output_size=(3, 3))
)

# training

In [44]:
loss = torch.nn.MSELoss()

In [45]:
model = Model(num_layers=20)
model.cuda()

Model(
  (rnn): GRU(71, 100, num_layers=20)
  (fc1): Linear(in_features=9, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=128, bias=True)
  (fc4): Linear(in_features=128, out_features=7, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.01, inplace=False)
  (avgpool): AdaptiveAvgPool2d(output_size=(3, 3))
)

In [46]:
dataset = Dataset(df, apply_normalize=True)

In [47]:
optimizer = torch.optim.Adam([
    dict(params=model.parameters(), lr=4e-4),
])

In [48]:
from tqdm import tqdm 

In [49]:
# train model for N epochs
max_valid_score = 0
EPOCH = 100
for epoch in range(EPOCH):

    torch.cuda.empty_cache()

    total_loss = 0
    for i in tqdm(range(len(dataset))):
        optimizer.zero_grad()     #optimizer gradient to zero

        # Get data
        x, y = dataset[500]
        x = torch.tensor(x, dtype=torch.float).unsqueeze(dim=1).cuda()
        y = torch.tensor(y, dtype=torch.float).cuda()

        # Train 

        ## 1. forward propagationreal_labels
        ## -----------------------

        pred = model(x)

        ## 2. loss calculation
        ## -----------------------
        _loss = loss(pred, y)

        # track loss
        total_loss += _loss.item()

        ## 3. backward propagation
        ## -----------------------
        _loss.backward()     


        ## 4. weight optimization
        ## -----------------------        
        optimizer.step()
        

#     if epoch %100 == 0:
    print("Epoch:", epoch, "Training Loss: {}".format(total_loss) )
        
    total_loss = 0



  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 0 Training Loss: 2199389170.2380905


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 1 Training Loss: 309922.3185258433


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 2 Training Loss: 260630.36027770117


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 3 Training Loss: 305347.68105372787


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 4 Training Loss: 329667.05232108384


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 5 Training Loss: 305702.9704671055


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 6 Training Loss: 338096.2776113227


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 7 Training Loss: 342688.9734996259


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 8 Training Loss: 387783.27540110797


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 9 Training Loss: 362788.78946521133


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 10 Training Loss: 422602.4537176937


  0%|          | 0/470 [00:00<?, ?it/s]

Epoch: 11 Training Loss: 367399.0898528546


 53%|█████▎    | 251/470 [01:05<00:57,  3.83it/s]


KeyboardInterrupt: 

# Test

In [212]:
x, y = dataset[400]
x = torch.tensor(x, dtype=torch.float).unsqueeze(dim=1).cuda()
y = torch.tensor(y, dtype=torch.float).cuda()

In [213]:
pred = model(x)
pred

tensor([3302.6318, 3701.5271, 3818.2429, 3802.4138, 4552.2139, 4278.9951,
        4181.1538], device='cuda:0', grad_fn=<AddBackward0>)

In [214]:
y

tensor([3622., 3947., 4241., 4085., 4626., 4951., 3983.], device='cuda:0')

In [215]:
pred - y

tensor([-319.3682, -245.4729, -422.7571, -282.5862,  -73.7861, -672.0049,
         198.1538], device='cuda:0', grad_fn=<SubBackward0>)

In [216]:
loss(pred, y)

tensor(131018.7734, device='cuda:0', grad_fn=<MseLossBackward>)

In [ ]:
# fc result
# Training Loss: 92919.921875 
# gru fc result
# 92851.1484375